config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/search',  to: 'search#search'
  get    '/recommend', to: 'recommend#index'

  resources :users do
    member do
      get :following, :followers, :media, :likes
    end
  end

  resources :microposts,          only: [:create, :destroy, :show] do    
    resources :comments,          only: [:create, :destroy]
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]

  namespace :api do

    resources :microposts, only: [] do
      resource :likes, only: [:create, :destroy], module: :microposts
    end
    resources :comments, only: [] do
      resource :likes, only: [:create, :destroy], module: :comments
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                :integer          not null, primary key
#  name              :string
#  email             :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  password_digest   :string
#  remember_digest   :string
#  admin             :boolean          default(FALSE)
#  activation_digest :string
#  activated         :boolean          default(FALSE)
#  activated_at      :datetime
#  reset_digest      :string
#  reset_sent_at     :datetime
#  avatar            :string
#  description       :text
#

class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liked_microposts, through: :likes, source: :likeable, source_type: "Micropost"
  has_many :liked_comments, through: :likes, source: :likeable, source_type: "Comment"

  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy                               
  has_many :following, through: :active_relationships, source: :followed                                
  has_many :followers, through: :passive_relationships, source: :follower

  attr_accessor :remember_token, :activation_token, :reset_token
  mount_uploader :avatar, AvatarUploader
  before_save   :downcase_email
  before_create :create_activation_digest

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
 
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password                
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validate  :avatar_size

  # 返回指定字符串的哈希摘要
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # 返一個隨機令牌
  def User.new_token
    SecureRandom.urlsafe_base64   
  end

  # 爲了持久保持會話，在數據庫中記住用戶
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 如果指定的令牌和摘要匹配，返回true
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # 激活账户
  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  # 发送激活邮件
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end
  
  # 忘记用户
  def forget
    update_attribute(:remember_digest, nil)
  end

  # 设置密码重设相关的属性
  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest:  User.digest(reset_token), reset_sent_at: Time.zone.now)
  end

  # 发送密码重设邮件
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  
  # 如果密码重设请求超时了，返回 true
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end 
  
   # 返回用户的动态流
  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end

  # 关注另一个用户
  def follow(other_user)
    following << other_user
  end

  # 取消关注另一个用户
  def unfollow(other_user)
    following.delete(other_user)
  end

   # 如果当前用户关注了指定的用户，返回 true
  def following?(other_user)
    following.include?(other_user)
  end

  # 判断是否已喜欢
  def liked?(likeable_obj)
    send("liked_#{downcase_class_name(likeable_obj)}s").include?(likeable_obj)
  end

  # 点赞
  def add_like(likeable_obj)
    send("liked_#{downcase_class_name(likeable_obj)}s") << likeable_obj
  end

  #取消赞
  def remove_like(likeable_obj)
    send("liked_#{downcase_class_name(likeable_obj)}s").delete(likeable_obj)
  end

  

  # 返回有图片的微博
  def media
    Micropost.where("picture is not null AND user_id = ?", id)
  end

  # 随机返回用户
  def people_to_follow(number)
    User.where.not(id: following_ids + [self.id]).limit(number).order("RANDOM()")
  end
    

  private

    # 把电子邮件地址转换成小写
    def downcase_email
      self.email = email.downcase
    end

    # 小写类名
    def downcase_class_name(obj)
      obj.class.to_s.downcase
    end

     # 创建并赋值激活令牌和摘要
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end

    # 验证上传的图像大小
    def avatar_size
      if avatar.size > 5.megabytes
        errors.add(:avatar, "should be less than 5MB")
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy,
                                        :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  

  def index
    @users = User.where(activated: true).paginate(page: params[:page])
  end

	def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
    redirect_to root_url and return unless @user.activated?
  end

  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])  
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  def likes
    @user = User.find(params[:id])
    @microposts = @user.liked_microposts.paginate(page: params[:page])
    render 'show'
  end

  def media
    @user = User.find(params[:id])
    @microposts = @user.media.paginate(page: params[:page])
    render 'show'
  end
  
  private

  	def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :description, :avatar)
    end

    # 前置过滤器

    

    # 确保是正确的用户
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

     # 确保是管理员
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def avatar_for(user, options = { size: 80 })
    size = options[:size]
    style = options[:style]
    if user.avatar?
      if size <= 80
        image_tag user.avatar.url(:thumb), width: size, height: size, alt: user.name, class: 'avatar', style: style
      else
        image_tag user.avatar.url, width: size, height: size, alt: user.name, class: 'avatar', style: style
      end
    else
      image_tag 'default-avatar.svg', width: size, height: size, alt: 'avatar image', class: 'avatar', style: style
    end
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
	<%= hidden_field_tag :followed_id, user.id %>
	<%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form-<%= @user.id %>">
  <% if current_user.following?(@user) %>
    <%= render partial: 'unfollow', locals: { user: @user } %>
  <% else %>
    <%= render partial: 'follow', locals: { user: @user } %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: user.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= avatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div class="user-avatar-edit">
        <label class="change-avatar" id="change-avatar" style="background-image: url('<%= @user.avatar.url %>')">
         <span class="file"><%= f.file_field :avatar %></span>
         <%= fa_icon "camera" %>             
        </label>
      </div>

      <%= f.text_area :description, rows: 3, autofocus: true, placeholder: "Tell the world about yourself!", class: 'form-control' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
    <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>
<div class="row">
	<div class="col-md-4">
		<aside class="user">
			<section class="user_info">
				<h1>
					<%= avatar_for @user %>
					<%= @user.name %>
				</h1>
			</section>
			<section class="stats">
	      <%= render 'shared/stats' %>
	    </section>
  	</aside>
	</div>
	  <div class="col-md-8">
	  <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <span class="ProfileHeading">
      	<ul class="nav nav-pills">
				  <li><a href="<%= user_path(@user) %>">Mypage</a></li>
				  <li><a href="<%= likes_user_path(@user) %>">Likes</a></li>
				  <li><a href="<%= media_user_path(@user) %>">Media</a></li>
				</ul>
      </span>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <div class="col-md-4">
    <aside>
      <section class="user_info">
        <%= avatar_for @user %>
        <h1><%= @user.name %></h1>
        <span><%= link_to "view my profile", @user %></span>
        <span><b>Microposts:</b> <%= @user.microposts.count %></span>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
        <% if @users.any? %>
          <div class="user_avatars">
            <% @users.each do |user| %>
              <%= link_to avatar_for(user, size: 30), user %>
            <% end %>
          </div>
        <% end %>
      </section>
  </aside>
  </div>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>