config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/search',  to: 'search#search'
  get    '/recommend', to: 'recommend#index'

  resources :users do
    member do
      get :following, :followers, :media, :likes
    end
  end

  resources :microposts,          only: [:create, :destroy, :show] do    
    resources :comments,          only: [:create, :destroy]
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]

  namespace :api do

    resources :microposts, only: [] do
      resource :likes, only: [:create, :destroy], module: :microposts
    end
    resources :comments, only: [] do
      resource :likes, only: [:create, :destroy], module: :comments
    end
  end
end

app/views/shared/_comment_form.html.erb
<%= form_for([@micropost, current_user.comments.build]) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= hidden_field_tag :micropost_id, @micropost.id %>
  <%= link_to avatar_for(current_user, size: 50), current_user %>
 	<div class="field">
  <%= f.text_area :content, placeholder: "Compose new comment..." %>
	</div>

  <%= f.submit "Publish", class: "btn btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<div class="modal fade" id="micropost_form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title text-center" id="myModalLabel">write a new micropost</h4>
            </div>
            <div class="modal-body micropost_form">
                <%= form_for(current_user.microposts.build) do |f| %>
                  <%= render 'shared/error_messages', object: f.object %>
                  <div class="field">
                    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
                  </div>    
                    <label class="picture">
                    <span class="file"><%= f.file_field :picture, 
                    accept: 'image/jpeg,image/gif,image/png' %></span>
                    <%= fa_icon "picture-o", class: "fa-2x" %>
                    </label>
                   <%= f.submit "Post", class: "btn btn-primary" %>
                <% end %>
            </div>
            
        </div><!-- /.modal-content -->
    </div><!-- /.modal -->
</div>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_recommend.html.erb
<% if logged_in? %>
<div class="recommend-users" >
	<h2>Recommend Users</h2>
	<span class="pull-right"><%= link_to "VIEW MORE", recommend_path %></span>
	<ul>
	<% @users.each do |user| %>
	<li>
		<%= link_to avatar_for(user, size: 30), user %>
		<span><%= user.name %></span>
		<span id="follow_form-<%= user.id %>">
		<%= render partial: 'users/follow', locals: { user: user }  %>
		</span>
	</li>
	<% end %>
	</ul>
</div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following-<%= @user.id %>" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers-<%= @user.id %>" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

<div class="description">
    <text><%= @user.description if @user.description?%></text>
</div>

app/views/shared/_user_info.html.erb
<%= link_to avatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>