config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/search',  to: 'search#search'
  get    '/recommend', to: 'recommend#index'

  resources :users do
    member do
      get :following, :followers, :media, :likes
    end
  end

  resources :microposts,          only: [:create, :destroy, :show] do    
    resources :comments,          only: [:create, :destroy]
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]

  namespace :api do

    resources :microposts, only: [] do
      resource :likes, only: [:create, :destroy], module: :microposts
    end
    resources :comments, only: [] do
      resource :likes, only: [:create, :destroy], module: :comments
    end
  end
end

app/models/micropost.rb
# == Schema Information
#
# Table name: microposts
#
#  id         :integer          not null, primary key
#  content    :text
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  picture    :string
#

class Micropost < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable
  has_many :likers, through: :likes, source: :user
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validate  :picture_size

  private

    # 验证上传的图像大小
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/api/microposts/likes_controller.rb
class Api::Microposts::LikesController < ApplicationController
	before_action :logged_in_user, only: [:create, :destroy]

	def create
		@micropost = Micropost.find(params[:micropost_id])
		current_user.add_like(@micropost)
		respond_to do |format|
      format.html { redirect_to request.referrer || root_url }
      format.js
    end
	end

	def destroy
		@micropost = Micropost.find(params[:micropost_id])
		current_user.remove_like(@micropost)
		respond_to do |format|
      format.html { redirect_to request.referrer || root_url }
      format.js
    end
	end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy
  

  def show
    @micropost = Micropost.find(params[:id])
    @comments = @micropost.comments.paginate(page: params[:page])
  end

  def create
  	@micropost = current_user.microposts.build(micropost_params)
  	if @micropost.save
  		flash[:success] = "Micropost created!"
      redirect_to root_url
     else
      @feed_items = current_user.feed.paginate(page: params[:page])
      redirect_to root_url
    end
  end

  def destroy
    Micropost.find_by(id: params[:id]).destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  private

  	def micropost_params
      params.require(:micropost).permit(:content, :picture)
    end

    def correct_user
      if current_user.admin?
        @micropost = Micropost.find_by(id: params[:id])
      else 
        @micropost = current_user.microposts.find_by(id: params[:id])
        redirect_to root_url if @micropost.nil?
      end
    end
end
	

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_likes.html.erb
<span id="likes-<%= micropost.id %>">
	<% if current_user.liked?(micropost) %>
		<%= link_to api_micropost_likes_path(micropost), method: :delete, remote: true do %>
		<%= fa_icon "heart" %>
		<% end %>
	<% else %>
		<%= link_to api_micropost_likes_path(micropost), method: :post, remote: true do %>
			<%= fa_icon "heart-o" %>
		<% end %>
	<% end %>
	<%= micropost.likes.count %>
</span>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to avatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="pull-right">
  <% if current_user.admin? || current_user?(micropost.user) %>
        <%= link_to "delete", micropost, method: :delete,
                                         data: { confirm: "You sure?" } %>
  <% end %>
  </span>
  <span class="content">
    <text><%= micropost.content %></text>
    <%= image_tag micropost.picture.url if micropost.picture? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>

  <div>
    <span class="link"><%= link_to  micropost do %> 
        <%= fa_icon "comments" %>
    <% end %>
    <%= micropost.comments.count %>
    </span>
    <span class="likes">
        <%= render partial: 'microposts/likes', locals: { micropost: micropost } %>
    </span>
  </div>
</li>

app/views/microposts/show.html.erb
<div class= "row">
  <div class="col-md-12">
    <div class="microposts microposts-show" id="micropost-<%= @micropost.id %>">
      <%= link_to avatar_for(@micropost.user, size: 50), @micropost.user %>
      <span class="user"><%= link_to @micropost.user.name, @micropost.user %></span>
      <span class="content">
        <%= @micropost.content %>
        <%= image_tag(@micropost.picture.url) if @micropost.picture? %>
      </span>
      <span class="timestamp">
        Posted <%= time_ago_in_words(@micropost.created_at) %> ago.
        <% if current_user?(@micropost.user) %>
          <%= link_to "delete", @micropost, method: :delete,
                                           data: { confirm: "You sure?" } %>
        <% end %>
      </span>
    </div>

    <% if logged_in? %>
      <div class="comment_form">
        <%= render 'shared/comment_form' %>
      </div>
    <% else %>
      <div class="login_sinup">
        <%= link_to "Login", login_path %> | 
        <%=link_to "SignUp", signup_path %>  
      </div>
    <% end %>

    <div class="comments">
      <h2><strong><%= @micropost.comments.count %></strong> 
      Comments</h2>
      <% if @comments.any? %>
        <ol>
          <%= render @comments %>
        </ol>
        <%= will_paginate @comments %>
      <% end %>
    </div>
  </div>
</div>