config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/search',  to: 'search#search'
  get    '/recommend', to: 'recommend#index'

  resources :users do
    member do
      get :following, :followers, :media, :likes
    end
  end

  resources :microposts,          only: [:create, :destroy, :show] do    
    resources :comments,          only: [:create, :destroy]
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]

  namespace :api do

    resources :microposts, only: [] do
      resource :likes, only: [:create, :destroy], module: :microposts
    end
    resources :comments, only: [] do
      resource :likes, only: [:create, :destroy], module: :comments
    end
  end
end

app/views/layouts/_alert_messages.html.erb
<% flash.each do |message_type, message | %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The sample app by izumi
  </small>
  <nav>
    <ul>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>      
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
  
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/search' %>
        <% if logged_in? %>
          <% if current_user.admin? %>          
            <li><%= link_to "Users", users_path %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
          <li class="top-avatar">
            <%= link_to avatar_for(current_user, size: 30), current_user %>
          </li>
          <li>
            <button class="btn btn-primary navbar-btn" data-toggle="modal" data-target="#micropost_form">Post</button>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>





<div class="modal fade" id="micropost_form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title text-center" id="myModalLabel">write a new micropost</h4>
            </div>
            <div class="modal-body micropost_form">
                <%= form_for(Micropost.new) do |f| %>
                  <%= render 'shared/error_messages', object: f.object %>
                  <div class="field">
                    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
                  </div>    
                    <label class="picture">
                    <span class="file"><%= f.file_field :picture, 
                    accept: 'image/jpeg,image/gif,image/png' %></span>
                    <%= fa_icon "picture-o", class: "fa-2x" %>
                    </label>
                   <%= f.submit "Post", class: "btn btn-primary" %>
                <% end %>
            </div>
            
        </div><!-- /.modal-content -->
    </div><!-- /.modal -->
</div>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/layouts/_rails_default.html.erb
 <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_search.html.erb
<li class="search">
  <%= form_tag search_path , :method => :get do %>
    <div class="input-group" id="search-id">
      <input type="text" class="form-control" name="q" placeholder="search">
        <div class="input-group-btn">
          <button class="btn btn-default" type="submit">
            <i class="glyphicon glyphicon-search"></i>
          </button>
      </div>
    </div>
  <% end %>
</li>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
	<%= render 'layouts/header' %>

	<div class="container">
    <% flash.each do |message_type, message | %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
	</div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
	<%= render 'layouts/header' %>

	<div class="container">
    <%= render 'layouts/alert_messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
	</div>
  </body>
</html>